/**
 * GET /api/threats/job?jobId=cg-xxx
 * Polls pipeline, auto-saves to Supabase, emits socket events to refresh pages.
 */

import { NextRequest, NextResponse } from 'next/server'
import { getAgentJob } from '@/lib/agent-client'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const savedJobs = new Set<string>()

export async function GET(request: NextRequest) {
    const jobId = request.nextUrl.searchParams.get('jobId')
    if (!jobId) return NextResponse.json({ success: false, error: 'jobId required' }, { status: 400 })

    try {
        const job = await getAgentJob(jobId)

        if (job.status === 'completed' && job.result && !savedJobs.has(jobId)) {
            savedJobs.add(jobId)

            // Save and emit — fire and forget so polling stays fast
            saveAndNotify(jobId, job.result).catch(err => {
                console.error(`[Job ${jobId}] Save failed:`, err.message)
                savedJobs.delete(jobId) // allow retry
            })
        }

        return NextResponse.json({ success: true, job })
    } catch (error: any) {
        console.error('[API] Poll error:', error)
        return NextResponse.json({ success: false, error: error.message }, { status: 500 })
    }
}


async function saveAndNotify(jobId: string, result: any) {
    const now = new Date().toISOString()
    const summary = { threats: 0, risks: 0, incidents: 0, playbooks: 0, reports: 0 }

    console.log(`[Save ${jobId}] Keys:`, Object.keys(result))

    // ── 1. Threats ────────────────────────────────────────────────────────
    for (const t of result.threats ?? []) {
        const { error } = await supabase.from('Threat').insert({
            id:          `thr-${jobId}-${rand()}`,
            threatId:    `THR-AI-${rand().toUpperCase()}`,
            type:        t.indicator_type  ?? 'malware',
            severity:    priorityToSeverity(t.priority_score ?? 50),
            source:      t.threat_actor    ?? 'AI Agent',
            target:      t.indicator_value ?? 'Unknown',
            detected:    now,
            status:      'mitigating',
        })
        if (error) console.error('[Save] Threat:', error.message)
        else summary.threats++
    }

    // ── 2. Risk Analysis ──────────────────────────────────────────────────
    for (const r of result.risk_register ?? []) {
        const { error } = await supabase.from('RiskAnalysis').insert({
            id:             `risk-${jobId}-${rand()}`,
            asset:          r.asset_name      ?? 'Unknown Asset',
            riskLevel:      Math.min(100, Math.round(r.risk_score ?? 0)),
            vulnerabilities: 1,
            exposureTime:   'Active',
            recommendation: r.score_breakdown ?? `Risk score: ${r.risk_score}`,
        })
        if (error) console.error('[Save] Risk:', error.message)
        else summary.risks++
    }

    // ── 3. Incidents for risk >= 50 ───────────────────────────────────────
    for (const r of (result.risk_register ?? []).filter((r: any) => (r.risk_score ?? 0) >= 50)) {
        const { error } = await supabase.from('Incident').insert({
            id:          `inc-${jobId}-${rand()}`,
            incidentId:  `INC-AI-${Date.now()}`,
            title:       `[AI] ${r.cve_id ?? 'Vulnerability'} on ${r.asset_name ?? 'Unknown Asset'}`,
            description: `Risk ${r.risk_score}/100. MITRE: ${r.mitre_tactic ?? 'N/A'}.`,
            severity:    (r.severity_label ?? 'high').toLowerCase(),
            status:      'open',
            assignee:    'Unassigned',
            created:     now,
            updated:     now,
        })
        if (error) console.error('[Save] Incident:', error.message)
        else summary.incidents++
    }

    // ── 4. Playbooks ──────────────────────────────────────────────────────
    for (const p of result.playbooks ?? []) {
        const { error } = await supabase.from('Playbook').insert({
            id:          `pb-${jobId}-${rand()}`,
            playbookId:  `PB-${rand().toUpperCase()}`,
            title:       p.incident_title   ?? `[AI] ${p.cve_id ?? 'Threat'} Response Playbook`,
            description: p.incident_summary ?? 'Auto-generated by CyberGuard AI IR Agent',
            category:    'AI Generated',
            steps:       (p.playbook?.containment?.length ?? 0) + (p.playbook?.eradication?.length ?? 0),
            content:     p.playbook ?? {},
            updatedBy:   'CyberGuard AI',
            lastUpdated: now,
        })
        if (error) console.error('[Save] Playbook:', error.message)
        else summary.playbooks++
    }

    // ── 5. Report ─────────────────────────────────────────────────────────
    const exec = result.executive_report ?? {}
    const tech = result.technical_report ?? {}
    const comp = result.compliance_report ?? {}

    if (exec.top_risk || tech.total_findings) {
        const { error } = await supabase.from('Report').insert({
            id:        `rep-${jobId}`,
            reportId:  `REP-${rand().toUpperCase()}`,
            title:     `AI Analysis Report — ${new Date().toLocaleDateString('en-US', { dateStyle: 'medium' })}`,
            type:      'executive',
            status:    'final',
            content:   { 
                executive_report: exec, 
                technical_report: tech, 
                compliance_report: comp,
                description: exec.top_risk ?? 'Full security posture and remediation analysis.'
            },
            jobId:     jobId,
            generated: now,
            threats:   summary.threats,
            resolved:  0
        })
        if (error) console.error('[Save] Report:', error.message)
        else summary.reports++
    }

    // ── 6. Mark job done ──────────────────────────────────────────────────
    await supabase.from('agent_jobs')
        .update({ status: 'completed', completed_at: now })
        .eq('job_id', jobId)

    console.log(`[Save ${jobId}] Complete:`, summary)

    // ── 7. Emit socket events to refresh all affected pages ───────────────
    await emitRefreshEvents(result, summary, exec)
}


async function emitRefreshEvents(result: any, summary: any, exec: any) {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'

    const emit = async (event: string, data: any) => {
        try {
            await fetch(`${appUrl}/api/internal/socket-emit`, {
                method:  'POST',
                headers: { 'Content-Type': 'application/json' },
                body:    JSON.stringify({ event, data }),
            })
        } catch (e) {
            console.warn(`[Socket] ${event} failed`)
        }
    }

    // Dashboard metrics update
    await emit('metrics:update', {
        postureScore:   exec.posture_score                ?? 0,
        criticalCount:  exec.severity_summary?.critical   ?? 0,
        highCount:      exec.severity_summary?.high       ?? 0,
        totalFindings:  result.technical_report?.total_findings ?? 0,
        topRisk:        exec.top_risk                     ?? '',
        actionRequired: exec.action_required              ?? '',
    })

    // Tell each page to refetch its data
    if (summary.threats   > 0) await emit('page:refresh', { page: 'threats' })
    if (summary.risks     > 0) await emit('page:refresh', { page: 'risk-analysis' })
    if (summary.incidents > 0) await emit('page:refresh', { page: 'incident-response' })
    if (summary.playbooks > 0) await emit('page:refresh', { page: 'playbooks' })
    if (summary.reports   > 0) await emit('page:refresh', { page: 'reports' })

    // Alert banner for dashboard
    await emit('alert:new', {
        id:        `alert-${Date.now()}`,
        type:      'analysis_complete',
        title:     'AI Analysis Saved',
        message:   `${summary.threats} threats · ${summary.risks} risks · ${summary.incidents} incidents · ${summary.playbooks} playbooks`,
        severity:  (exec.severity_summary?.critical ?? 0) > 0 ? 'critical' : 'info',
        timestamp: new Date().toISOString(),
    })
}

const rand = () => Math.random().toString(36).slice(2, 7)

function priorityToSeverity(score: number): string {
    if (score >= 80) return 'critical'
    if (score >= 60) return 'high'
    if (score >= 40) return 'medium'
    return 'low'
}

function exploitabilityLabel(score: number): string {
    if (score >= 9) return 'PUBLIC'
    if (score >= 5) return 'POC_ONLY'
    if (score >= 1) return 'THEORETICAL'
    return 'NONE'
}
