/**
 * GET /api/threats/job?jobId=cg-xxx
 * Polls the Python agent pipeline, then saves ALL results to the DB
 * tables that the other pages (Threats, Risk Analysis, Incidents, Playbooks) read from.
 */

import { NextRequest, NextResponse } from 'next/server'
import { getAgentJob } from '@/lib/agent-client'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }
)

export async function GET(request: NextRequest) {
    const jobId = request.nextUrl.searchParams.get('jobId')

    if (!jobId) {
        return NextResponse.json(
            { success: false, error: 'jobId query param required' },
            { status: 400 }
        )
    }

    try {
        const job = await getAgentJob(jobId)

        if (job.status === 'completed' && job.result) {
            await Promise.allSettled([
                saveResultsToDB(jobId, job.result),
                pushToSocket(job.result),
            ])
        }

        return NextResponse.json({ success: true, job })

    } catch (error: any) {
        console.error('[API] Error polling job:', error)
        return NextResponse.json(
            { success: false, error: error.message },
            { status: 500 }
        )
    }
}


async function saveResultsToDB(jobId: string, result: any) {
    const now = new Date().toISOString()

    // 1. Save raw threats from Threat Intelligence Agent
    const threats: any[] = result.threats ?? []
    for (const t of threats) {
        const threatId = `thr-agent-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
        await supabase.from('Threat').insert({
            id: threatId,
            title: `Agent Detected: ${t.indicator_value ?? t.indicator_type ?? 'Unknown'}`,
            description: `MITRE Tactic: ${t.mitre_tactic ?? 'Unknown'} | Technique: ${t.mitre_technique_id ?? 'N/A'}`,
            severity: priorityToSeverity(t.priority_score ?? 50),
            status: 'active',
            source: 'AI Agent',
            cveId: t.indicator_type === 'cve' ? t.indicator_value : null,
            ipAddress: t.indicator_type === 'ip' ? t.indicator_value : null,
            detected: now,
        })
    }

    // 2. Save risk findings from Risk Analysis Agent
    const riskRegister: any[] = result.risk_register ?? []
    for (const r of riskRegister) {
        const riskId = `risk-agent-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
        await supabase.from('RiskAnalysis').insert({
            id: riskId,
            assetId: r.asset_id ?? 'unknown',
            assetName: r.asset_name ?? 'Unknown Asset',
            riskLevel: Math.round(r.risk_score ?? 0),
            cvssScore: r.cvss_score ?? null,
            exploitability: exploitabilityLabel(r.exploitability_score),
            patchAvailable: r.patch_available ?? false,
            scoreBreakdown: `CVSS:${r.cvss_score} | Exploit:${r.exploitability_score} | Asset:${r.asset_criticality_score} | ThreatIntel:${r.threat_intel_score}`,
            mitreAttack: r.mitre_tactic ?? null,
            created: now,
        })
    }

    // 3. Auto-create Incidents for CRITICAL findings (risk >= 70)
    const criticalFindings = riskRegister.filter(r => (r.risk_score ?? 0) >= 70)
    for (const r of criticalFindings) {
        const incId = `inc-agent-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
        await supabase.from('Incident').insert({
            id: incId,
            incidentId: `INC-AGENT-${Date.now()}`,
            title: `[AI] ${r.cve_id ?? 'Vulnerability'} on ${r.asset_name ?? 'Unknown Asset'}`,
            description: `Risk score ${r.risk_score}/100. MITRE: ${r.mitre_tactic ?? 'N/A'}. Auto-created by AI agent pipeline.`,
            severity: 'critical',
            status: 'open',
            assignee: 'AI Agent (Unassigned)',
            created: now,
            updated: now,
        })
    }

    // 4. Save AI-generated Playbooks
    const playbooks: any[] = result.playbooks ?? []
    for (const p of playbooks) {
        const pbId = `pb-agent-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
        await supabase.from('Playbook').insert({
            id: pbId,
            title: `[AI] ${p.cve_id ?? 'Threat'} Response Playbook`,
            description: 'Auto-generated by CyberGuard AI Incident Response Agent',
            category: 'AI Generated',
            content: JSON.stringify(p.playbook ?? {}),
            cveId: p.cve_id ?? null,
            lastUpdated: now,
            created: now,
        })
    }

    // 5. Save report
    const execReport = result.executive_report ?? {}
    const techReport = result.technical_report ?? {}
    if (execReport.top_risk || techReport.total_findings) {
        await supabase.from('Report').insert({
            id: `rep-agent-${jobId}`,
            title: `AI Analysis Report — ${new Date().toLocaleDateString()}`,
            type: 'executive',
            status: 'final',
            content: JSON.stringify({ executive_report: execReport, technical_report: techReport }),
            generated: now,
        })
    }

    // 6. Mark job done
    await supabase
        .from('agent_jobs')
        .update({ status: 'completed', completed_at: new Date().toISOString() })
        .eq('job_id', jobId)

    console.log(`[DB] Saved: ${threats.length} threats, ${riskRegister.length} risks, ${criticalFindings.length} incidents, ${playbooks.length} playbooks`)
}


async function pushToSocket(result: any) {
    try {
        const execReport = result.executive_report ?? {}
        const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'
        await fetch(`${APP_URL}/api/internal/socket-emit`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                event: 'agent:complete',
                data: {
                    result: {
                        threats:     result.threats       ?? [],
                        risk_scores: result.risk_register ?? [],
                        metrics: {
                            postureScore:   execReport.posture_score                ?? 0,
                            criticalCount:  execReport.severity_summary?.critical   ?? 0,
                            highCount:      execReport.severity_summary?.high       ?? 0,
                            totalFindings:  result.technical_report?.total_findings ?? 0,
                            topRisk:        execReport.top_risk                     ?? '',
                            actionRequired: execReport.action_required              ?? '',
                        },
                    },
                },
            }),
        })
    } catch (e) {
        console.warn('[API] Socket push failed (non-critical):', e)
    }
}

function priorityToSeverity(score: number): string {
    if (score >= 80) return 'critical'
    if (score >= 60) return 'high'
    if (score >= 40) return 'medium'
    return 'low'
}

function exploitabilityLabel(score: number): string {
    if (score >= 9) return 'PUBLIC'
    if (score >= 5) return 'POC_ONLY'
    if (score >= 1) return 'THEORETICAL'
    return 'NONE'
}
